apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: nginx
          image: personil/porsev-nginx:<TAG>
          resources:
            requests:
              cpu: "1"
              memory: "1G"
            limits:
              cpu: "2"
              memory: "2G"
          ports:
            - containerPort: 80